using Jellyfin.Plugin.ThemeForge.Engines.Discovery;
using Xunit;

namespace Jellyfin.Plugin.ThemeForge.Tests;

/// <summary>
/// Covers reading a music release's track, artist and album out of yt-dlp's output.
/// </summary>
public class MusicCreditsTests
{
    private const string Description =
        "Provided to YouTube by La-La Land Records\n\n"
        + "Main Title · Bear McCreary\n\n"
        + "Battlestar Galactica: Season 1 (Original Soundtrack)\n\n"
        + "℗ 2005 La-La Land Records\n\n"
        + "Released on: 2005-06-07\n\n"
        + "Auto-generated by YouTube.";

    [Fact]
    public void TheDistributorBlockYieldsAllThree()
    {
        var (track, artist, album) = YtDlpJson.ReadMusicCredits(Description);

        Assert.Equal("Main Title", track);
        Assert.Equal("Bear McCreary", artist);
        Assert.Equal("Battlestar Galactica: Season 1 (Original Soundtrack)", album);
    }

    [Fact]
    public void AnOrdinaryDescriptionYieldsNothing()
    {
        var (track, artist, album) = YtDlpJson.ReadMusicCredits("My upload of the intro. Like and subscribe.");

        Assert.Null(track);
        Assert.Null(artist);
        Assert.Null(album);
    }

    [Fact]
    public void NothingYieldsNothing() =>
        Assert.Equal((null, null, null), YtDlpJson.ReadMusicCredits(null));

    [Fact]
    public void ExplicitFieldsWinOverTheDescription()
    {
        var json = """
            {"id": "abcdefghijk", "title": "Main Title", "channel": "Bear McCreary - Topic",
             "album": "Battlestar Galactica: Season 1", "artist": "Bear McCreary", "track": "Main Title",
             "description": "Provided to YouTube by X\n\nOther · Someone\n\nOther Album"}
            """;

        var candidate = YtDlpJson.ParseOne(json, TestData.DefaultQuery, hydrated: true)!;

        Assert.Equal("Battlestar Galactica: Season 1", candidate.Album);
        Assert.Equal("Bear McCreary", candidate.Artist);
        Assert.Equal("Main Title", candidate.Track);
        Assert.True(candidate.IsTopicChannel);
    }

    [Fact]
    public void TheDescriptionFillsInWhenTheFieldsAreMissing()
    {
        var json = """{"id": "abcdefghijk", "title": "Main Title", "channel": "Bear McCreary - Topic", "description": "PLACEHOLDER"}"""
            .Replace("PLACEHOLDER", Description.Replace("\n", "\\n"), System.StringComparison.Ordinal);

        var candidate = YtDlpJson.ParseOne(json, TestData.DefaultQuery, hydrated: true)!;

        Assert.Equal("Battlestar Galactica: Season 1 (Original Soundtrack)", candidate.Album);
        Assert.Equal("Bear McCreary", candidate.Artist);
    }

    [Fact]
    public void AFlatResultIsNotATopicUploadUnlessItsChannelSaysSo()
    {
        var candidate = YtDlpJson.ParseOne(
            """{"id": "abcdefghijk", "title": "Firefly theme", "channel": "Some Reactor"}""",
            TestData.DefaultQuery,
            hydrated: false)!;

        Assert.False(candidate.IsTopicChannel);
        Assert.Null(candidate.Album);
    }
}
